(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function l(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ba(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function n(a){return a instanceof Array?a:ba(l(a))}function p(){}var q=[];
function ca(a,b){if(!b||"function"!==typeof b)return!1;try{var c=""+b}catch(h){return!1}var d=c.length;if(d>35+a.length)return!1;for(var e=d-13,f=0,g=8;g<d;g+=1){f="[native code]"[f]===c[g]||7===f&&"-"===c[g]?f+1:0;if(12===f)return!0;if(!f&&g>e)break}return!1}function r(a,b){var c=ca(a,b);b&&!c&&q.push([a,b]);return c}function u(a,b){return r(b,a)&&a}var da=u(String.prototype.indexOf,"indexOf");
function ea(a,b){for(var c=0,d=a.length-b.length,e=0;e<a.length;e+=1){c=a[e]===b[c]?c+1:0;if(c===b.length)return e-b.length+1;if(!c&&e>d)break}return-1}var fa=da?function(a,b){return da.call(a,b)}:ea;function ha(a,b){return!(!a||-1===fa(a,b))}function ia(a){return"[object Array]"===Object.prototype.toString.call(a)}var ja=u(Array.isArray,"isArray"),ka=ja?function(a){return ja(a)}:ia;function v(a){return function(b){return function(c){return a(b,c)}}}
function w(a){return function(b){return function(c){return a(c,b)}}}var la=v(function(a,b){return a===b}),x=v(function(a,b){return b(a)}),ma=la(null);function y(a){return"function"===typeof a}var z=la(void 0);function na(a){return z(a)||ma(a)}var qa=u(Array.from,"from");function ra(a){for(var b=a.length,c=[],d=0;d<b;d+=1)c.push(a[d]);return c}function A(a){if(qa)try{return qa(a)}catch(b){}return ra(a)}
function sa(a,b,c){b=void 0===b?[]:b;c=c||{};var d=b.length,e=a;y(e)&&(e="d",c[e]=a);var f;d?1===d?f=c[e](b[0]):2===d?f=c[e](b[0],b[1]):3===d?f=c[e](b[0],b[1],b[2]):4===d&&(f=c[e](b[0],b[1],b[2],b[3])):f=c[e]();return f}var ta=u(Function.prototype.bind,"bind");
function ua(){var a=A(arguments);a=l(a);var b=a.next().value,c=a.next().value,d=ba(a);return function(){var e=[].concat(n(d),n(A(arguments)));if(Function.prototype.call)return Function.prototype.call.apply(b,[c].concat(n(e)));if(c){for(var f="_b";c[f];)f+="_"+f.length;c[f]=b;e=c[f]&&sa(f,e,c);delete c[f];return e}return sa(b,e)}}var B=ta?function(){var a=A(arguments),b=l(a);a=b.next().value;var c=b.next().value;b=ba(b);return ta.apply(a,[c].concat(b))}:ua;
function C(a,b){return B.apply(null,[b,null].concat(n(a)))}function D(a,b){return B(b,null,a)}function E(a,b){return B(b[a],b)}var va=u(Array.prototype.reduce,"reduce");function wa(a,b,c){for(var d=0,e=c.length;d<e;)b=a(b,c[d],d),d+=1;return b}var F=va?function(a,b,c){return va.call(c,a,b)}:wa,xa=Object.prototype.hasOwnProperty;function G(a,b){return na(a)?!1:xa.call(a,b)}
function H(a,b){if(!a)return null;var c=b.split("."),d=c.length,e=a,f=0;try{for(;f<d;){if(null===e||void 0===e)return e;e=e[c[f]];f+=1}}catch(g){return null}return e}var I=w(H);function ya(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return c;return-1}var za;function Aa(a){if(za)return za;var b=!1;try{b=[].indexOf&&0===[void 0].indexOf(void 0)}catch(d){}var c=a.Array&&a.Array.prototype&&u(a.Array.prototype.indexOf,"indexOf");return za=a=b&&c?function(d,e){return c.call(e,d)}:ya}var Ba=Aa(window);
function J(a){return a}function Ca(a,b){return b}function Da(a){return!a}function K(a,b){var c=[],d=[];var e=b?b:J;return function(){var f=A(arguments),g=e.apply(null,n(f)),h=Ba(g,d);if(-1!==h)return c[h];f=a.apply(null,n(f));c.push(f);d.push(g);return f}}
var Ea=K(I("navigator.userAgent")),Fa=w(parseInt)(10),Ga=/Firefox\/([0-9]+)/i,Ha=K(function(a){var b=H(a,"document.documentElement.style"),c=H(a,"InstallTrigger");a=-1!==(H(a,"navigator.userAgent")||"").toLowerCase().search(Ga);Ga.lastIndex=0;return!(!(b&&"MozAppearance"in b)||na(c))||a});function Ia(a,b){var c=H(b,a),d=H(b,"constructor.prototype."+a)||c;try{if(d&&d.apply)return function(){return d.apply(b,arguments)}}catch(e){return c}return d}
function Ja(){var a=Array.prototype.map;if(!Ha(window))return!0;try{a.call({0:!0,length:-Math.pow(2,32)+1},function(){throw 1;})}catch(b){return!1}return!0}var Ka=u(Array.prototype.map,"map");function La(a,b){return F(function(c,d,e){c.push(a(d,e));return c},[],b)}var L=Ka&&Ja()?function(a,b){return b&&0<b.length?Ka.call(b,a):[]}:La,Ma=w(L);function M(){var a=arguments,b=a[0];return function(){for(var c=b.apply(null,arguments),d=a.length,e=1;e<d;)c=a[e](c),e+=1;return c}}var Na=v(C),Oa=v(E);
function Pa(a,b,c){return c?a:b}C([1,null],Pa);C([1,0],Pa);var Qa=Boolean,Ra=u(Array.prototype.filter,"filter");function Sa(a,b){return wa(function(c,d,e){a(d,e)&&c.push(d);return c},[],b)}var Ta=Ra?function(a,b){return Ra.call(b,a)}:Sa,Ua=D(Qa,Ta),Va=u(Array.prototype.includes,"includes");function Wa(a,b){return 1<=Sa(la(a),b).length}var Xa=Va?function(a,b,c){return Va.call(b,a,c)}:Wa,Ya=u(Object.keys,"keys");function Za(a){var b=[],c;for(c in a)G(a,c)&&b.push(c);return b}
var $a=u(Object.entries,"entries");function ab(a){return z(a)?[]:wa(function(b,c){b.push([c,a[c]]);return b},[],Za(a))}var bb=$a?function(a){return a?$a(a):[]}:ab,cb=Ya?function(a){return Ya(a)}:Za;function db(){var a=A(arguments),b=l(a);a=b.next().value;for(b=ba(b);b.length;){var c=b.shift(),d;for(d in c)G(c,d)&&(a[d]=c[d]);G(c,"toString")&&(a.toString=c.toString)}return a}var N=Object.assign||db;function eb(a){var b=[];a.forEach(function(c){b.push(c)});return b}
function fb(a){if(!a)return[];if(ka(a))return a;if(qa)try{return qa(a)}catch(b){}return"number"===typeof a.size&&y(a.add)?eb(a):"number"===typeof a.length&&0<=a.length?ra(a):[]}var gb=u(Array.prototype.some,"some");function hb(a,b){for(var c=0;c<b.length;c+=1)if(c in b&&a.call(b,b[c],c))return!0;return!1}
var ib=gb?function(a,b){return gb.call(b,a)}:hb,jb=K(M(I("String.fromCharCode"),D("fromCharCode",r),Da)),kb=K(M(Ea,E("test",/ipad|iphone|ipod/i))),lb=K(function(a){a=(Ea(a)||"").toLowerCase();return ha(a,"android")&&ha(a,"mobile")}),mb=K(M(I("document.addEventListener"),Da));I("top.contentWindow");function nb(a){return kb(a)||lb(a)||/mobile/i.test(Ea(a))||!z(H(a,"orientation"))}
var ob=K(function(a){a=!(!a.addEventListener||!a.removeEventListener);return{la:a,g:a?"addEventListener":"attachEvent",X:a?"removeEventListener":"detachEvent"}});function pb(a,b,c,d,e,f){a=ob(a);var g=a.g,h=a.X;f=f?h:g;if(b[f])if(a.la)if(e)b[f](c,d,e);else b[f](c,d);else b[f]("on"+c,d)}
var qb=K(function(a){var b=!1;if(!a.addEventListener)return b;try{var c=Object.defineProperty({},"passive",{get:function(){b=!0;return 1}});a.addEventListener("test",p,c)}catch(d){}return b}),rb=v(function(a,b){if(null!==b)return a?N({capture:!0,passive:!0},b||{}):!!b}),sb=K(function(a){var b=qb(a),c=rb(b),d={};return N(d,{g:function(e,f,g,h){L(function(k){var m=c(h);pb(a,e,k,g,m,!1)},f);return B(d.na,d,e,f,g,h)},na:function(e,f,g,h){L(function(k){var m=c(h);pb(a,e,k,g,m,!0)},f)}})});
function tb(a,b){L(M(J,E("push",a)),b)}var ub=K(function(a){a=a.Ya=a.Ya||{};var b=a._metrika=a._metrika||{};return{xa:function(c,d){G(b,c)||(b[c]=d);return this},B:function(c,d){b[c]=d;return this},l:function(c,d){var e=b[c];return G(b,c)||z(d)?e:d}}}),vb=K(function(a){return a.id+":"+a.T});function wb(a,b){for(var c="",d=0;d<b.length;d+=1)c+=""+(d?a:"")+b[d];return c}var xb=u(Array.prototype.join,"join"),O=xb?function(a,b){return xb.call(b,a)}:wb,yb="hash host hostname href pathname port protocol search".split(" ");
function P(a){return F(function(b,c){var d=H(a,"location."+c);b[c]=d?""+d:"";return b},{},yb)}var zb=/^\s+|\s+$/g,Ab=u(String.prototype.trim,"trim");function Bb(a){return Ab?Ab.call(a):(""+a).replace(zb,"")}var Cb=v(function(a,b){return b.replace(a,"")}),Db=Cb(/\s/g),Q=Cb(/\D/g),Eb=["metrika_enabled"],Fb=[];function Gb(a,b){var c=Hb;return!Fb.length||Xa(b,Eb)?!0:F(function(d,e){return d&&e(a,c,b)},!0,Fb)}
function Ib(a){try{var b=a.document.cookie;if(!na(b)){var c={};L(function(d){var e=l(d.split("="));d=e.next().value;e=e.next().value;d=d?Bb(d):"";var f="";try{f=decodeURIComponent(e)}catch(g){}e=(e=f)?Bb(e):"";c[d]=e},(b||"").split(";"));return c}}catch(d){}return null}var Jb=function(a,b,c){return function(){var d=ub(arguments[0]),e=c?"global":"m2490",f=d.l(e,{}),g=H(f,a);g||(g=K(b),f[a]=g,d.B(e,f));return g.apply(null,arguments)}}("gsc",Ib);
function Hb(a,b){var c=Jb(a);return c?c[b]||null:null}var Kb=/:\d+$/;function Lb(a,b,c,d,e,f,g){g=void 0===g?!1:g;if(Gb(a,b)){var h=b+"="+encodeURIComponent(c)+";";if(d){var k=new Date;k.setTime(k.getTime()+6E4*d);h+="expires="+k.toUTCString()+";"}e&&(d=e.replace(Kb,""),h+="domain="+d+";");try{a.document.cookie=h+("path="+(f||"/")),g||(Jb(a)[b]=c)}catch(m){}}}
var Mb=K(function(a){var b=(P(a).host||"").split(".");return 1===b.length?b[0]:F(function(c,d,e){e+=1;2<=e&&!c&&(e=O(".",b.slice(-e)),Lb(a,"metrika_enabled","1",0,e,void 0,!0),(d=(d=Ib(a))&&d.metrika_enabled)&&Lb(a,"metrika_enabled","",-100,e,void 0,!0),d&&(c=e));return c},"",b)});
function Nb(a,b,c){b=void 0===b?"_ym_":b;c=void 0===c?"":c;var d=Mb(a),e=1===(d||"").split(".").length?d:"."+d,f=c?"_"+c:"";return{da:function(g,h,k){Lb(a,""+b+g+f,"",-100,h||e,k,!1);return this},l:function(g){return Hb(a,""+b+g+f)},B:function(g,h,k,m,t){Lb(a,""+b+g+f,h,k,m||e,t);return this}}}
var Ob=K(Nb),Pb=K(function(a){var b=Ob(a),c="1"===b.l("debug"),d=P(a).href;(d=-1<fa(d,"_ym_debug=1"))||(d=P(a).href,d=-1<fa(d,"_ym_debug=2"));var e=a._ym_debug;!e&&!d||c||(a=P(a),b.B("debug","1",void 0,a.host));return!!(c||e||d)});mb(window);var Qb=["http.0.st..rt.","network error occurred","send beacon","Content Security Policy","DOM Exception 18"];function R(a){throw a;}var U;function Rb(a){this.message=a}
var Sb=function(a){return function(b,c){c=void 0===c?!1:c;if(U)var d=new U(b);else r("Error",a.Error)?(U=a.Error,d=new a.Error(b)):(U=Rb,d=new U(b));c&&(d.unk=!0);return d}}(window),Tb=E("test",RegExp("^http."));function Ub(a){var b="";ka(a)?b=O(".",a):"string"===typeof a&&(b=a);return Sb("err.kn(2490)"+b)}var Vb=E("test",RegExp("^err.kn"));function V(a,b){return b?a(b):a()}var Wb=[];
function Xb(a){a=H(a,"performance")||H(a,"webkitPerformance");var b=H(a,"timing.navigationStart"),c=H(a,"now");c&&(c=B(c,a));return[b,c]}function Yb(a,b){var c=l(b||Xb(a)),d=c.next().value;c=c.next().value;return!isNaN(d)&&y(c)?Math.round(c()+d):a.Date.now?a.Date.now():(new a.Date).getTime()}
function W(a,b,c){var d=c||R;return function(){var e=void 0;try{e=d.apply(null,arguments)}catch(k){var f=k,g="u.a.e",h="";f&&("object"===typeof f?(f.unk&&R(f),g=f.message,h="string"===typeof f.stack&&f.stack.replace(/\n/g,"\\n")||"n.s.e.s"):g=""+f);Vb(g)||ib(D(g,ha),Qb)||Tb(g)&&.1<=a.Math.random()||L(M(J,Na(["jserrs",g,b,h]),V),Wb)}return e}}function Zb(a,b){return function(){return W(arguments[0],a,b).apply(this,arguments)}}
function $b(a){return F(function(b,c){var d=l(c),e=d.next().value,f=d.next().value;d=f.ga;f=a[f.ka];b[e]=d?d(f):f;return b},{},bb(ac))}function bc(a,b){if(!b)return null;try{return a.JSON.parse(b)}catch(c){return null}}function cc(a,b){try{return a.JSON.stringify(b,null,void 0)}catch(c){return null}}function dc(a){try{return a.localStorage}catch(b){}return null}function ec(a,b){var c=dc(a);try{c.removeItem(b)}catch(d){}}
function fc(a,b){var c=dc(a);try{return bc(a,c.getItem(b))}catch(d){}return null}function gc(a,b,c){var d=dc(a);a=cc(a,c);if(!ma(a))try{d.setItem(b,a)}catch(e){}}var hc=K(function(a){gc(a,"_ymBRC","1");var b="1"!==fc(a,"_ymBRC");b||ec(a,"_ymBRC");return b}),ic=K(function(a,b,c){var d=""+(void 0===c?"_ym":c)+(void 0===b?"":b);d&&(d+="_");return{ta:hc(a),l:function(e,f){var g=fc(a,""+d+e);return ma(g)&&!z(f)?f:g},B:function(e,f){gc(a,""+d+e,f);return this},da:function(e){ec(a,""+d+e);return this}}});
function jc(a){if(na(a))return!1;a=a.nodeType;return 3===a||8===a}var kc=K(M(I("document"),D("createElement",Ia)));function lc(a){var b=z(void 0);if(z(void 0)&&b){b=1;var c=1073741824}else b=b?1:void 0,c=void 0;return a.Math.floor(a.Math.random()*(c-b))+b}function mc(a){return(10>a?"0":"")+a}function nc(a){var b=a.O;return 0!==b?b:Yb(a.G,a.s)}
var oc=K(function(a){var b=sb(a),c=Xb(a),d={G:a,O:0,s:c,sa:Yb(a,c)},e=l(c);c=e.next().value;e=e.next().value;c&&e||b.g(a,["beforeunload","unload"],function(){0===d.O&&(d.O=Yb(a,d.s))});return x(d)});function X(a,b,c,d){return Ia("setTimeout",a)(W(a,d+".d.err",b),c)}function pc(a,b){return function(c){return c(a,b)}}
function qc(a,b){function c(f){H(d,e)&&(d.nodeType?d.src===H(d,"contentDocument.URL"):1)?f():X(a,D(f,c),100,b+".wfb")}var d=void 0===d?a:d;var e=(d.nodeType?"contentWindow.":"")+"document.body";return x(function(f,g){c(g)})}function rc(a){var b=[],c={wa:b};c.g=M(E("push",b),D(c,J));c.X=M(w(Aa(a))(b),w(E("splice",b))(1),D(c,J));c.trigger=M(J,w(V),Ma(b));return c}I("postMessage");x(function(a){return-(new a.G.Date).getTimezoneOffset()});
x(function(a){a=new a.G.Date;return O("",L(mc,[a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds()]))});x(function(a){return Math.round(nc(a)/1E3)});D("5re7z1tl8cfx3k7uosg",J);D("2490",J);I("navigator.cookieEnabled");I("devicePixelRatio");var sc=[],tc=[],uc=[],vc=[],wc=setTimeout;function xc(){}function yc(a,b){return function(){a.apply(b,arguments)}}
function Y(a){if(!(this instanceof Y))throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this.m=0;this.P=!1;this.v=void 0;this.D=[];zc(a,this)}function Ac(a,b){for(;3===a.m;)a=a.v;0===a.m?a.D.push(b):(a.P=!0,Y.R(function(){var c=1===a.m?b.ia:b.ja;if(null===c)(1===a.m?Bc:Cc)(b.promise,a.v);else{try{var d=c(a.v)}catch(e){Cc(b.promise,e);return}Bc(b.promise,d)}}))}
function Bc(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");if(b&&("object"===typeof b||"function"===typeof b)){var c=b.then;if(b instanceof Y){a.m=3;a.v=b;Dc(a);return}if("function"===typeof c){zc(yc(c,b),a);return}}a.m=1;a.v=b;Dc(a)}catch(d){Cc(a,d)}}function Cc(a,b){a.m=2;a.v=b;Dc(a)}function Dc(a){2===a.m&&0===a.D.length&&Y.R(function(){a.P||Y.ca(a.v)});for(var b=0,c=a.D.length;b<c;b++)Ac(a,a.D[b]);a.D=null}
function Ec(a,b,c){this.ia="function"===typeof a?a:null;this.ja="function"===typeof b?b:null;this.promise=c}function zc(a,b){var c=!1;try{a(function(d){c||(c=!0,Bc(b,d))},function(d){c||(c=!0,Cc(b,d))})}catch(d){c||(c=!0,Cc(b,d))}}Y.prototype["catch"]=function(a){return this.then(null,a)};Y.prototype.then=function(a,b){var c=new this.constructor(xc);Ac(this,new Ec(a,b,c));return c};
Y.prototype["finally"]=function(a){var b=this.constructor;return this.then(function(c){return b.resolve(a()).then(function(){return c})},function(c){return b.resolve(a()).then(function(){return b.reject(c)})})};
Y.all=function(a){return new Y(function(b,c){function d(h,k){try{if(k&&("object"===typeof k||"function"===typeof k)){var m=k.then;if("function"===typeof m){m.call(k,function(t){d(h,t)},c);return}}e[h]=k;0===--f&&b(e)}catch(t){c(t)}}if(!a||"undefined"===typeof a.length)return c(new TypeError("Promise.all accepts an array"));var e=Array.prototype.slice.call(a);if(0===e.length)return b([]);for(var f=e.length,g=0;g<e.length;g++)d(g,e[g])})};
Y.resolve=function(a){return a&&"object"===typeof a&&a.constructor===Y?a:new Y(function(b){b(a)})};Y.reject=function(a){return new Y(function(b,c){c(a)})};Y.race=function(a){return new Y(function(b,c){if(!a||"undefined"===typeof a.length)return c(new TypeError("Promise.race accepts an array"));for(var d=0,e=a.length;d<e;d++)Y.resolve(a[d]).then(b,c)})};Y.R="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){wc(a,0)};
Y.ca=function(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)};var Z=window.Promise,Fc=u(Z,"Promise"),Gc=u(H(Z,"resolve"),"resolve"),Hc=u(H(Z,"reject"),"reject"),Ic=u(H(Z,"all"),"all");if(Fc&&Gc&&Hc&&Ic){var Jc=function(a){return new Promise(a)};Jc.resolve=B(Gc,Z);Jc.reject=B(Hc,Z);Jc.all=B(Ic,Z);Z=Jc}else Z=Y;function Kc(a){return a.N||a.V.length<=a.J}function Lc(a){a.N=!0}function Mc(a){a.N=!1}
function Nc(a){Kc(a)&&R(Sb("i"));var b=a.ea(a.V[a.J]);a.J+=1;return b}var Oc=v(function(a,b){for(var c=[];!Kc(b);){var d=Nc(b);a(d,function(e){return e(b)});c.push(d)}return c});function Pc(a,b){return function(c){var d=oc(a),e=d(nc);return Oc(function(f,g){d(nc)-e>=b&&g(Lc)})(c)}}
var Qc=/^\d+$/,Rc={id:function(a){a=""+(a||"0");Qc.test(a)||(a="0");try{var b=Fa(a)}catch(c){b=0}return b},T:function(a){return""+(a||0===a?a:"0")},fa:Qa,oa:Qa},ac=F(function(a,b){var c=l(b),d=c.next().value;c=c.next().value;a[d]={ka:c,ga:Rc[d]};return a},{},bb({id:"id",oa:"ut",T:"type",va:"ldc",fa:"nck",ra:"url",qa:"referrer"}));B(Z.reject,Z,Ub());var Sc=K(Zb("dc.init",function(){return{log:p,warn:p,error:p}}),Ca);function Tc(a,b,c,d){Sc(a,b).log(c,d)}
function Uc(a,b){var c=ub(a).l("counters",{}),d=vb(b);return c[d]}function Vc(a,b){b=void 0===b?p:b;var c=void 0===c?!1:c;var d=rc(a);if(q&&y(q.push)){var e=q.push;q.push=function(){var f=A(arguments),g=l(f).next().value;c&&d.trigger(g);f=e.apply(q,f);c||d.trigger(g);return f};b({ha:d,unsubscribe:function(){q.push=e}});L(d.trigger,q)}}function Wc(a,b){return function(c){var d=c[a];d?(d.Z=!0,d.Y(b)):c[a]={promise:Z.resolve(b),Z:!0,Y:p}}}
var Xc=v(function(a,b){if(!b[a]){var c,d=new Z(function(e){c=e});b[a]={Y:c,promise:d,Z:!1}}return b[a].promise}),Yc=K(M(function(){return{}},x));function Zc(a,b){Yc()(Wc(a,b))}function $c(a,b){var c=vb(a);return Yc()(Xc(c)).then(b)}
function ad(a,b){if(a.postMessage&&!a.attachEvent){var c=sb(a),d="__ym__promise_"+lc(a)+"_"+lc(a),e=p;e=c.g(a,["message"],W(a,"a.ra",function(f){try{var g=f.data}catch(h){return}g===d&&(e(),f.stopPropagation&&f.stopPropagation(),b())}));a.postMessage(d,"*")}else X(a,b,0,"a.ra")}var bd=[],cd=!1,dd=!1;function ed(a,b){if(bd.length){var c=bd.shift();dd?c():X(a,c,100,b+".ei.rnt")}else cd=!1}
function fd(a,b,c,d){d=void 0===d?1:d;var e=void 0===e?Pc:e;dd=Infinity===d;return x(function(f,g){function h(){try{var m=b(e(a,d));k=k.concat(m)}catch(t){return f(t)}b(Mc);if(b(Kc))return g(k),ed(a,c);dd?(b(e(a,1E4)),g(k),ed(a,c)):X(a,h,100,c+".ei")}var k=[];cd?bd.push(h):(cd=!0,h())})}function gd(a,b,c,d,e,f){e=void 0===e?1:e;f=void 0===f?p:f;b=x({V:b,ea:c||J,N:!1,J:0});fd(a,b,d+".itc",e)(pc(W(a,d),f))}
function hd(a,b,c,d,e){function f(k){return y(d)?d(k)?a.NodeFilter.FILTER_ACCEPT:a.NodeFilter.FILTER_REJECT:a.NodeFilter.FILTER_ACCEPT}e=void 0===e?-1:e;var g=void 0===g?!1:g;var h=f(b);if(y(c)&&(g||h===a.NodeFilter.FILTER_ACCEPT)&&(h&&c(b),!jc(b)))for(b=a.document.createTreeWalker(b,e,d?{acceptNode:f}:null,!1);b.nextNode()&&!1!==c(b.currentNode););}var id=K(function(a){return O("[^\\d<>]*",a.split(""))}),jd=K(function(a){return new RegExp(id(a),"g")});
function kd(a){return new RegExp("(?:"+O("|",L(id,cb(a)))+")")}function ld(a){var b={7:"8",8:"7"};return 11===a.length&&b[a[0]]?""+b[a[0]]+a.slice(1):a}function md(a,b){for(var c=[],d=a.split(""),e=b.split(""),f=0,g=0;g<a.length&&!(f>=e.length);g+=1){var h=d[g];"0"<=h&&"9">=h?(c.push(e[f]),f+=1):c.push(d[g])}return O("",c)+b.slice(f+1)}function nd(){return C([function(a,b){var c=l(L(Q,b)),d=c.next().value;c=c.next().value;a[d]={A:c,K:b};var e=ld(d);e!==d&&(a[e]={A:ld(c),K:b});return a},{}],F)}
function od(a,b,c){if(!c)return[];var d=[],e=kd(b),f=["script","style"];hd(a,c,function(g){var h=H(g,"parentNode.nodeName")||"";g===c||Xa(h.toLowerCase(),f)||(h=Ua(e.exec(g.textContent||"")||[]),L(function(k){var m=Q(k);z(b[m])||d.push({M:"text",C:g,I:m,A:md(k,b[m].A),ma:g.textContent||""})},h))},function(g){return e.test(g.textContent||"")?1:0},a.NodeFilter.SHOW_TEXT);return d}
function pd(a,b){var c=a.document.body;if(!c)return[];var d=kd(b);return F(function(e,f){var g=H(f,"href");try{var h=decodeURI(g||"")}catch(S){h=""}var k=h;if("tel:"===k.slice(0,4)){var m=l(d.exec(k)||[]).next().value;h=m?Q(m):"";var t=b[h];z(t)||!h&&"*"!==t.K[0]||(e.push({M:"href",C:f,I:h,A:md(m,b[h].A),ma:g}),g=Q(k.slice(4)),g=nd()([h?t.K:[g,""]]),tb(e,od(a,g,f)))}return e},[],fb(c.querySelectorAll("a")))}
function qd(a,b,c){function d(k){return e(a,b,k)?h[k.I]&&h[k.I].K:null}var e=c.aa,f={},g=void 0===c.W?(f.href=!0,f.text=!0,f):c.W,h;return function(k){return new Z(function(m,t){k&&k.length||t();h=nd()(k);qc(a,"ph.r")(pc(D({j:[],s:0},m),function(){var S=oc(a),oa=S(nc),T=g.href?pd(a,h):[],pa=g.text?od(a,h,a.document.body):[];m({j:Ta(ka,Ua(L(d,T.concat(pa)))),s:S(nc)-oa})}))})}}function rd(a,b){sb(a).g(a,["load"],b.trigger)}
function sd(a,b){qc(a,"ph.s")(pc(p,function(){var c=a.document.body,d={};d=(d.attributes=!0,d.childList=!0,d.subtree=!0,d);r("MutationObserver",a.MutationObserver)&&(new MutationObserver(b.trigger)).observe(c,d)}))}function td(a,b,c){function d(){f=0;g&&(g=!1,f=X(a,d,1E3,c+".to.d"),e.trigger(h))}var e=rc(a),f,g=!1,h;b.g(function(k){g=!0;h=k;f||d();return p});return e}var ud=/\S/;
function vd(a,b,c,d){function e(){L(function(m){m.style&&N(m.style,{opacity:""})},fb(c.childNodes));if(b){var k=Uc(a,b);k&&k.extLink("tel:"+d,{})}g();h()}var f=sb(a),g=p,h=p;g=f.g(c,["mouseenter"],function(k){if(k.target===c){var m=X(a,e,200,"ph.h.e");h();h=f.g(c,["mouseleave"],function(t){t.target===c&&Ia("clearTimeout",a)(m)})}})}
var wd=D(["style","display:inline;margin:0;padding:0;font-size:inherit;color:inherit;line-height:inherit"],function(a,b){b=void 0===b?{}:b;if(!a||1>a.length)return b;F(function(c,d,e){if(e===a.length-1)return c;e===a.length-2?c[d]=a[e+1]:G(c,d)||(c[d]={});return c[d]},b,a);return b});
function xd(a,b,c){var d=kc(a),e=c.C,f=c.I,g=e.parentNode,h=e.textContent;if(!("text"===c.M&&h&&d&&g))return!1;c=d("small");wd(c);var k=Db(h).length;L(E("appendChild",c),F(function(m,t){var S=m.nodes,oa=m.ba,T=d("small");T.innerHTML=t;var pa=ud.test(t);wd(T);pa&&(T.style.opacity=""+(k-oa-1)/k);S.push(T);return{nodes:S,ba:oa+(pa?1:0)}},{nodes:[],ba:0},h).nodes);vd(a,b,c,f);g.insertBefore(c,e);e.textContent="";return!0}
function yd(a,b,c){var d={};b=qd(a,b,{aa:xd,W:(d.href=!0,d)});c=Ua(L(function(f){return"*"===f?f:Q(f)},c));var e=L(M(J,E("concat",[""]),Oa("reverse"),V),c);c=rc(a);d=td(a,c,"ph");b=D(e,b);d.g(b);rd(a,c);sd(a,c);b()}
var zd=K(function(a){var b;(b=jb(a))||(b=!(r("querySelectorAll",H(a,"Element.prototype.querySelectorAll"))&&a.document.querySelectorAll));return b}),Ad=Zb("phc.h",function(a,b){if(!nb(a)&&!zd(a))return $c(b,function(c){if(!H(c,"settings.phchange")){var d=ic(a),e=ha(P(a).search,"_ym_hide_phones=1")||d.l("hide_phones",0);c=H(c,"settings.phhide");e&&!c&&(c=["*"],d.B("hide_phones",1));c&&yd(a,b,c)}})["catch"](W(a,"phc.hs"))}),Bd=/[\*\.\?\(\)]/g,Cd=K(function(a,b,c){try{var d=c.replace("\\s"," ").replace(Bd,
"");b={};Sc(a,"").warn("nnw",(b.name=d,b))}catch(e){}},Ca),Dd=Zb("r.nn",function(a){Pb(a)&&Vc(a,function(b){b.ha.g(function(c){var d=l(c);c=d.next().value;d=d.next().value;Cd(a,d,c);q.splice(100)})})});D(Ub("ccf"),R);
function Ed(a,b,c,d,e){if(b.F&&b.H&&(b.F===a.F&&b.H===a.H||N(a,b,{j:{},L:!0}),0<e&&tb(a.s,[e]),L(function(f){var g=l(f);f=g.next().value;g=g.next().value;var h={},k={};N(a.j,(k[f]=(h[g]=+(a.j[f]&&a.j[f][g]?a.j[f][g]:0),h),k))},d),L(function(f){var g=l(f);f=g.next().value;g=g.next().value;var h={},k={};N(a.j,(k[f]=(h[g]=1+(a.j[f]?a.j[f][g]:0),h),k))},c),a.U&&(a.L||c.length))){if(b=Uc(a.G,a.S))c={},b.params("__ym","phc",(c.clientId=a.F,c.orderId=a.H,c.service_id=a.$,c.phones=a.j,c.performance=a.s,c));
a.L=!1}}var Fd=K(qd);function Gd(a,b,c){a=jd(c.I);if("href"===c.M){var d=c.C;b=d.href;c=b.replace(a,c.A);if(b!==c)return d.href=c,!0}else if((b=null===(d=c.C.textContent)||void 0===d?void 0:d.replace(a,c.A))&&b!==c.C.textContent)return c.C.textContent=b,!0;return!1}var Hd=K(bc,Ca);
function Id(a,b,c){b=Nb(a,void 0,b);b=Hd(a,b.l("phc_settings")||"");var d=H(b,"clientId"),e=H(b,"orderId"),f=H(b,"service_id"),g=H(b,"phones")||[];return d&&e&&g&&f?Fd(a,c.S,{aa:Gd})(g).then(function(h){return Ed(c,{F:d,H:e,$:f},h.j,g,h.s)})["catch"](p):Z.resolve()}
var Jd=Zb("phc.p",function(a,b){if(!zd(a))return $c(b,function(c){var d=b.id,e=Nb(a,void 0,d),f=e.l("phc_settings")||"";if(c=H(c,"settings.phchange")){var g=cc(a,c)||"";g!==f&&e.B("phc_settings",g)}else f&&(c=Hd(a,f));e=H(c,"orderId");f=H(c,"phones")||[];H(c,"clientId")&&e&&f.length&&(f={F:"",H:"",$:0,j:{},s:[],U:!1,L:!0,G:a,S:b},N(f,{U:!0}),Id(a,d,f),c=rc(a),e=td(a,c,"phc"),d=B(Id,null,a,d,f),e.g(d),sd(a,c))})}),Kd=ub(window),Ld=["tag_phone","js"].shift();ub(window);tc.push(Ad);Eb.push("_ym_debug");
vc.unshift(Dd);tc.push(Jd);
var Md=function(){var a=window;L(w(V)(a),vc);return W(window,"m."+Ld,function(b,c,d){var e=$b(b);"2490"!==d&&R(Sb("m.vc."+Ld));b=L(J,uc);d=vb(e);var f={};f=C([a,d,"imnc",(f.key=d,f.module="tag_phone.js",f)],Tc);c&&Zc(d,c);if(Kd.l("counters",{})[d]){L(function(k){k(a,e)},sc);var g=[],h=function(k){k&&(y(k)?g.push(k):y(k.then)?k.then(h):!ma(k)&&!z(k)&&"[object Object]"===Object.prototype.toString.call(k)&&k.u&&g.push(k.u))};c=function(k){k=k(a,e);h(k)};ad(a,C([a,b,c,"a.i",1],gd));L(c,tc);return C([V,
g],L)}f()})}(),Nd=Kd.l("ytmm",{});if(!Nd[Ld]){var Od={};Nd[Ld]=(Od.init=Md,Od);Kd.B("ytmm",Nd)};}).call(this);
